// SPDX-License-Identifier: Apache-2.0

plugins {
    id("typewright.kmp.pure")
    alias(libs.plugins.kotlin.serialization)
}

// Node-economy data packs, generated by data/scripts/build_node_economy_corpus.py and never
// hand-edited, reach this module as resources under typewright/corpus/. P1's loader
// (CorpusResources.kt / CorpusLoader.kt) reads them back by that same path.
val syncCorpusData =
    tasks.register<Sync>("syncCorpusData") {
        description = "Copies data/node-economy-*.json into this module's generated resources."
        from(isolated.rootProject.projectDirectory.dir("data")) {
            include("node-economy-*.json")
            into("typewright/corpus")
        }
        into(layout.buildDirectory.dir("generated/corpusData"))
    }

kotlin {
    sourceSets {
        commonMain {
            dependencies {
                api(project(":core-geometry"))
                // P1b: the style detector (dev.aarso.typewright.qa.corpus.style) builds its
                // glyph set from `core-font`'s SfntFont (StyleGlyphSet.fromSfntFont), so the
                // detector can run on an SfntFont directly rather than every caller first
                // converting to core-geometry Glyphs by hand.
                api(project(":core-font"))
                implementation(libs.kotlinx.serialization.json)
            }
            resources.srcDir(syncCorpusData)
        }
    }
}
