// SPDX-License-Identifier: Apache-2.0

package com.asoc.typewright.scripts.kana

import com.asoc.typewright.scripts.GlyphInventory
import com.asoc.typewright.scripts.GlyphSpec
import com.asoc.typewright.scripts.TemplateSheetEntry
import com.asoc.typewright.scripts.WritingScript

/**
 * One real kana glyph, as read from a real template in
 * `scripts/templates/hyle-all-templates.zip`'s `svg/Hiragana` or `svg/Katakana` folder --
 * [name], [unicodeName] and [codepoint] became [com.asoc.typewright.scripts.GlyphSpec]'s
 * fields; [templateFileName] plus the folder name became
 * [com.asoc.typewright.scripts.TemplateSheetEntry]'s.
 *
 * The literal [HIRAGANA_TEMPLATES] and [KATAKANA_TEMPLATES] lists below this type were generated
 * from `scripts/templates/kana-manifest.json` (itself generated by
 * `scripts/templates/generate_kana_manifest.py` directly from the real zip -- see that script's
 * own KDoc) and checked in as literal Kotlin per this build's established data-pack convention
 * (CLAUDE.md: "Data packs ... checked in ... with a generator script beside them; never hand-edit
 * generated data"); [KanaGlyphInventoryTest] and [KanaTemplateSheetTest] cross-check the counts,
 * codepoints and derived names this file carries against that same manifest's own facts (folder
 * counts 55/57, no duplicate codepoints, every name produced by [deriveKanaGlyphName]) so a
 * silent transcription slip would fail a test, not ship quietly.
 */
internal data class KanaTemplate(
    val name: String,
    val unicodeName: String,
    val codepoint: Int,
    val templateFileName: String,
)

internal fun List<KanaTemplate>.toGlyphInventory(script: WritingScript) =
    GlyphInventory(
        script = script,
        glyphs = map { GlyphSpec(name = it.name, unicodeName = it.unicodeName, codepoint = it.codepoint) },
    )

internal fun List<KanaTemplate>.toTemplateSheetEntries(templateFolder: String): List<TemplateSheetEntry> =
    map {
        TemplateSheetEntry(
            glyphName = it.name,
            templateFolder = templateFolder,
            templateFileName = it.templateFileName,
        )
    }

/**
 * Stated once here, plainly, rather than left implicit in each inventory's own KDoc: this
 * task's own instructions quote `docs/RESEARCH_font_quality.md`'s claim that "a complete kana
 * set is closer to ~200 glyphs than 92 once voiced/semi-voiced/small/historical forms are
 * counted", but also say the real inventory built here "should reflect the zip's real 55+57
 * Hiragana+Katakana template count, not invent additional coverage the templates don't have".
 * [HIRAGANA_TEMPLATES] and [KATAKANA_TEMPLATES] together carry exactly 112 real glyphs -- the
 * 46+46 base gojuon syllables, 9+9 small kana, the katakana middle dot and the shared
 * prolonged-sound mark -- and deliberately do NOT add voiced (が), semi-voiced (ぱ) or
 * historical (ゐ ゑ) forms as their own [GlyphSpec] entries, because no template for any of them
 * exists in the real zip. Voiced and semi-voiced forms are still real, coverable glyphs: per the
 * research ("Dakuten ... and handakuten ... sit at the upper right; they are encoded as
 * combining U+3099/U+309A") and this template pack's own `HOW_TO_USE.md` ("voiced forms compose
 * from the dakuten mark"), they compose at shaping time from a base kana plus a combining mark
 * (`KanaFeaturePlan.kt`'s `ccmp`/ligature-substitution stage), not from a second drawn outline
 * per syllable -- so their absence here is the real, templated 112-glyph starting inventory this
 * asset actually gives a drawer, not a silent shortfall against the research's own ~200 estimate.
 */
const val KANA_INVENTORY_SCOPE_NOTE: String =
    "112 real templates (55 Hiragana + 57 Katakana) cover the base gojuon syllables, small kana, " +
        "the katakana middle dot and the shared prolonged-sound mark. Voiced/semi-voiced/historical " +
        "forms (research: 'closer to ~200 glyphs than 92') are not separate templates in this pack " +
        "and are not invented here; they compose from a base kana plus a combining dakuten/" +
        "handakuten mark at shaping time instead (see KanaFeaturePlan.kt)."
